# Default values for aiops-cassandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/metrasensor/metra-aiops
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: major-latest

imagePullSecrets: metra-registry-secret
nameOverride: ""
fullnameOverride: ""