name: Linter of Helm charts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  helm-linter-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Lint Helm charts
        uses: helm/chart-testing-action@v2.2.0
        with:
          command: lint
          config: ct.yaml

# kubeval https://github.com/marketplace/actions/setup-kubeval
# kube-score https://github.com/marketplace/actions/kube-score-check