---
apiVersion: v1
kind: ConfigMap
metadata:
  name: { { include "aiops-alerts.fullname" . } }
  labels: { { - include "aiops-alerts.labels" . | nindent 4 } }
data:
  DEBUG_MODE: true
  CASSANDRA_CLUSTER: metra-cassandra
  KEYSPACE_NAME: aiops
  UDP_SERVER_IP: 0.0.0.0
  UDP_SERVER_PORT: 8094
  HTTP_SERVER_IP: 0.0.0.0
  HTTP_SERVER_PORT: 8095
  NATS_SERVERS: nats://metra-nats:4222
  RECEIVED_DATA_TTL: 864000
  TRIGGERED_ALERT_TTL: 864000
  PREDICTION_PERIODS: 40
  PREDICTION_FREQ: 5min
  PREDICTION_TTL: 1200
  WEBHOOK_MESSAGE_INTERVAL: 3600
  SUBJECT_ALERTS_NAME: alerts
  SUBJECT_PREDICTOR_NAME: predictor
  SUBJECT_WEBHOOKS_NAME: webhooks
