---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aiops-alerts.fullname" . }}
  labels: {{- include "aiops-alerts.labels" . | nindent 4 }}
data: {{- toYaml .Values.configmap | nindent 2 }}
